---
language: ruby
rvm:
  - 2.4.1
env:
  - PATH=$PATH:$HOME/bin
  - profile_name=default
  - results_path=cucumber-results.json
before_install:
  - sudo apt-get install ruby ruby-dev
  - gem update --system
  - mkdir -p $HOME/bin
install:
  - bundle
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar xvfz geckodriver-v0.23.0-linux64.tar.gz -C $HOME/bin
before_script:
script:
  - rubocop
  - cucumber --dry-run
  - cucumber -f json -o cucumber-results.json
after_success:
after_failure:
after_script:
  - [[ -f $results_path ]] || (echo "No results found at '$results_path'" && exit 1)
  - env |   grep --extended-regexp --ignore-case --invert-match "^.*(${mask}).*=" |   curl     --fail     --request POST     --form env=@-     --form "profileName=${profile_name}"     --form "payload=@${results_path};type=application/x.cucumber.rb.results+json"     "https://7a250c6e81fe86e232bdc93a084d86f8b29@app.cucumber.pro/tests/results/check-inbdd/$revision"
notifications:
