---
language: ruby
rvm:
  - 2.4.1
before_install:
  - sudo apt-get install ruby ruby-dev
  - gem update --system
install:
  - bundle
before_script:
script:
  - rubocop
  - cucumber --dry-run
after_success:
after_failure:
after_script:
notifications:
